In [1]:
import pandas as pd

Y1NB = pd.read_csv('final_predictions/Y1_NB.csv')
Y2   = pd.read_csv('final_predictions/Y2.csv')
Y1LG = pd.read_csv('final_predictions/Y1_LG.csv')

In [2]:
Y1LG.drop([c for c in ['Age','Sex','AvgTime','NumRaces','YrsSinceLast']],inplace=True,axis=1)

In [3]:
Y = Y1LG.copy().set_index('Id')

In [4]:
Y = Y.join(Y1NB.set_index('ID'))
Y['Y2']=-1.

In [5]:
Y2 = Y2.set_index('ID')

In [6]:
y2_indices = Y2.index.tolist()
y_indices  = Y.index.tolist()

In [7]:
for i in y2_indices:
    if i in y_indices:
        Y.set_value(i,'Y2',Y2.loc[i]['Y2'])

In [8]:
all_valid_y2_predictions = Y[Y['Y2']>0]['Y2'].values.tolist()
y2_avg = sum(all_valid_y2_predictions) / len(all_valid_y2_predictions)

In [9]:
invalid_y2 = Y[Y['Y2']==-1].index.tolist()

In [10]:
for i in invalid_y2:
    Y.set_value(i,'Y2',y2_avg)

In [15]:
for i in y_indices:
    t_n = Y.loc[i]['Y2']
    t   = t_n* (30282.-7942.)+7942.

    Y.set_value(i,'Y2',t)

In [18]:
Y

       Y1 Log Reg  Y1            Y2
Id
1               0   0  16290.234600
2               1   0  20191.692200
3               0   0  19136.574000
4               1   0  19814.593000
5               1   1  20844.690400
6               0   0  18357.801600
7               1   0  14383.515600
8               0   0  15385.017800
9               1   1  21245.693400
10              0   0  17917.927000
11              1   1  18732.666800
12              0   1  17808.862975
13              0   0  11900.424600
14              0   0  15256.116000
15              1   1  19710.488600
16              1   1  16131.620600
17              0   0  16006.740000
18              1   0  25798.362000
19              0   0  20030.844200
20              0   0  12239.099000
21              0   0  15900.625000
22              0   0  16483.028800
23              0   0  16757.810800
24              0   0  14553.969800
25              0   0  15797.190800
26              0   0  17553.114800
27              0   0  16741.949400
28              0   0  19993.089600
29              0   0  19824.646000
30              1   0  21188.726400
...           ...  ..           ...
30388           0   0  19608.171400
30389           0   0  17394.277400
30390           0   0  15693.086400
30391           0   0  19821.295000
30392           0   0  23284.665200
30393           0   0  15451.814400
30394           0   0  20073.066800
30395           0   0  16665.770000
30396           0   0  18811.080200
30397           0   0  18312.898200
30398           0   0  24899.847200
30399           0   0  16029.303400
30400           0   0  10974.208200
30401           0   0  15367.592600
30402           0   0  13859.195800
30403           0   0  20170.916000
30404           0   0  15432.602000
30405           0   0  13533.031800
30406           0   0  16043.154200
30407           0   0  16572.165400
30408           0   0  17316.534200
30409           0   0  15641.481000
30410           0   0  17293.747400
30411           0   0  21718.631200
30412           0   0  18461.012400
30413           0   0  16834.213600
30414           0   0  14925.484000
30415           0   0  15056.843200
30416           0   0  15111.576200
30417           0   0  11764.374000

[30417 rows x 3 columns]

In [17]:
Y.to_csv('data/predictions.csv')